### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by glf1030** [APMonitor/apm_python#4]
hi, I went through this problem after I have installed everything in my mac. I wonder  what the problem is ? How should I fix this. Thank you

**Comment by APMonitor** [comment]
It was a problem with relative paths that changed with a more recent version of Python. I fixed the issue by including apm.py in the run directories. You can also install APMonitor with "pip install APMonitor" and then replace the "from apm import *" with "from APMonitor.apm import *". A cleaner way to import the APMonitor package is to use "import APMonitor.apm as apm" and then call functions such as apm.solve('myproblem').
